/*
 * Bellese challenge
 * api for Bellese fullstack challenge
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BelleseChallenge);
  }
}(this, function(expect, BelleseChallenge) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Item', function() {
      beforeEach(function() {
        instance = new BelleseChallenge.Item();
      });

      it('should create an instance of Item', function() {
        // TODO: update the code to test Item
        expect(instance).to.be.a(BelleseChallenge.Item);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property picture (base name: "picture")', function() {
        // TODO: update the code to test the property picture
        expect(instance).to.have.property('picture');
        // expect(instance.picture).to.be(expectedValueLiteral);
      });

      it('should have the property keyValueFields (base name: "keyValueFields")', function() {
        // TODO: update the code to test the property keyValueFields
        expect(instance).to.have.property('keyValueFields');
        // expect(instance.keyValueFields).to.be(expectedValueLiteral);
      });

    });
  });

}));
