/*
 * Bellese challenge
 * api for Bellese fullstack challenge
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/KeyValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./KeyValue'));
  } else {
    // Browser globals (root is window)
    if (!root.BelleseChallenge) {
      root.BelleseChallenge = {};
    }
    root.BelleseChallenge.Item = factory(root.BelleseChallenge.ApiClient, root.BelleseChallenge.KeyValue);
  }
}(this, function(ApiClient, KeyValue) {
  'use strict';

  /**
   * The Item model module.
   * @module model/Item
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Item</code>.
   * @alias module:model/Item
   * @class
   * @param name {String} 
   * @param description {String} 
   * @param picture {String} 
   */
  var exports = function(name, description, picture) {
    this.name = name;
    this.description = description;
    this.picture = picture;
  };

  /**
   * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Item} obj Optional instance to populate.
   * @return {module:model/Item} The populated <code>Item</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('picture'))
        obj.picture = ApiClient.convertToType(data['picture'], 'String');
      if (data.hasOwnProperty('keyValueFields'))
        obj.keyValueFields = ApiClient.convertToType(data['keyValueFields'], [KeyValue]);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} picture
   */
  exports.prototype.picture = undefined;

  /**
   * @member {Array.<module:model/KeyValue>} keyValueFields
   */
  exports.prototype.keyValueFields = undefined;

  return exports;

}));
