// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Bellese challenge
api for Bellese fullstack challenge


    Schemes:
      http
    Host: localhost:59828
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
