// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteItemIDHandlerFunc turns a function with the right signature into a delete item ID handler
type DeleteItemIDHandlerFunc func(DeleteItemIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteItemIDHandlerFunc) Handle(params DeleteItemIDParams) middleware.Responder {
	return fn(params)
}

// DeleteItemIDHandler interface for that can handle valid delete item ID params
type DeleteItemIDHandler interface {
	Handle(DeleteItemIDParams) middleware.Responder
}

// NewDeleteItemID creates a new http.Handler for the delete item ID operation
func NewDeleteItemID(ctx *middleware.Context, handler DeleteItemIDHandler) *DeleteItemID {
	return &DeleteItemID{Context: ctx, Handler: handler}
}

/*DeleteItemID swagger:route DELETE /item/{id} deleteItemId

DeleteItemID delete item ID API

*/
type DeleteItemID struct {
	Context *middleware.Context
	Handler DeleteItemIDHandler
}

func (o *DeleteItemID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteItemIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
