// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/wobenshain/fullstack-developer-challenge/go/restapi/models"
)

// DeleteItemIDAcceptedCode is the HTTP code returned for type DeleteItemIDAccepted
const DeleteItemIDAcceptedCode int = 202

/*DeleteItemIDAccepted remove an item

swagger:response deleteItemIdAccepted
*/
type DeleteItemIDAccepted struct {
}

// NewDeleteItemIDAccepted creates DeleteItemIDAccepted with default headers values
func NewDeleteItemIDAccepted() *DeleteItemIDAccepted {

	return &DeleteItemIDAccepted{}
}

// WriteResponse to the client
func (o *DeleteItemIDAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

/*DeleteItemIDDefault generic error response

swagger:response deleteItemIdDefault
*/
type DeleteItemIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteItemIDDefault creates DeleteItemIDDefault with default headers values
func NewDeleteItemIDDefault(code int) *DeleteItemIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteItemIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete item ID default response
func (o *DeleteItemIDDefault) WithStatusCode(code int) *DeleteItemIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete item ID default response
func (o *DeleteItemIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete item ID default response
func (o *DeleteItemIDDefault) WithPayload(payload *models.Error) *DeleteItemIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete item ID default response
func (o *DeleteItemIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteItemIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
