// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetItemIDHandlerFunc turns a function with the right signature into a get item ID handler
type GetItemIDHandlerFunc func(GetItemIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetItemIDHandlerFunc) Handle(params GetItemIDParams) middleware.Responder {
	return fn(params)
}

// GetItemIDHandler interface for that can handle valid get item ID params
type GetItemIDHandler interface {
	Handle(GetItemIDParams) middleware.Responder
}

// NewGetItemID creates a new http.Handler for the get item ID operation
func NewGetItemID(ctx *middleware.Context, handler GetItemIDHandler) *GetItemID {
	return &GetItemID{Context: ctx, Handler: handler}
}

/*GetItemID swagger:route GET /item/{id} getItemId

GetItemID get item ID API

*/
type GetItemID struct {
	Context *middleware.Context
	Handler GetItemIDHandler
}

func (o *GetItemID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetItemIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
