// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/wobenshain/fullstack-developer-challenge/go/restapi/models"
)

// NewPostItemParams creates a new PostItemParams object
// no default values defined in spec.
func NewPostItemParams() PostItemParams {

	return PostItemParams{}
}

// PostItemParams contains all the bound params for the post item operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostItem
type PostItemParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the item to create
	  In: body
	*/
	Item *models.Item
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostItemParams() beforehand.
func (o *PostItemParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Item
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("item", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Item = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
